name: clone-the-stage
run-name: ${{ github.actor }} is cloning the stage
on: [push, delete]
jobs:
  clone_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Clone Repo
      run: git clone https://github.com/ScenarioHunting/sh-stage.git

