name: clone-the-stage
run-name: ${{ github.actor }} is cloning the stage
on: [push, delete]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ScenarioHunting/sh-stage'
          ref: 'master'
